[Eth]
NetworkId = 977
SyncMode = "fast"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
Etherbase = "0x1949789ff7b51175a3adaf7cdcaa20a51b85b3b6"
GasFloor = 8000000
GasCeil = 8000000
GasPrice = 0
Recommit = 3000000000
Noverify = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
CachesLockMmap = false
DatasetDir = "/Users/mohamedaimendjari/Library/Ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
DatasetsLockMmap = false
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
DataDir = "test2"
omitempty = ""
IPCPath = "geth.ipc"
HTTPHost = "192.168.1.94"
HTTPPort = 8557
HTTPCors = ["*"]
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = ["enode://ad997f3ba319e289a8968e10eb29842deba3e900e62c34b8bef7921cbad259c8e404bdca3e8320b362b384da0a85a923a8120980a554dee309ceabda549eb45a@127.0.0.1:0?discport=30301"]
BootstrapNodesV5 = ["enode://ad997f3ba319e289a8968e10eb29842deba3e900e62c34b8bef7921cbad259c8e404bdca3e8320b362b384da0a85a923a8120980a554dee309ceabda549eb45a@127.0.0.1:0?discport=30301"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":30306"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000
